import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || 'https://lumovia-stream-omega.vercel.app').replace(/\/$/, '');

  return {
    rules: [
      // Block aggressive SEO/scraper bots that burn API quota
      { userAgent: 'AhrefsBot',       disallow: '/' },
      { userAgent: 'SemrushBot',      disallow: '/' },
      { userAgent: 'MJ12bot',         disallow: '/' },
      { userAgent: 'DotBot',          disallow: '/' },
      { userAgent: 'BLEXBot',         disallow: '/' },
      { userAgent: 'PetalBot',        disallow: '/' },
      { userAgent: 'YandexBot',       disallow: '/' },
      { userAgent: 'Baiduspider',     disallow: '/' },
      { userAgent: 'Bytespider',      disallow: '/' },
      { userAgent: 'GPTBot',          disallow: '/' },
      { userAgent: 'ClaudeBot',       disallow: '/' },
      { userAgent: 'anthropic-ai',    disallow: '/' },
      { userAgent: 'CCBot',           disallow: '/' },
      { userAgent: 'DataForSeoBot',   disallow: '/' },
      {
        userAgent: '*',
        allow: [
          '/',
          '/browse',
          '/blog',
          '/genre/',
          '/details/',
          '/person/',
          '/movie/',
          '/tv/',
          '/anime/',
          '/actor/',
          '/country/',
          '/language/',
          '/studio/',
          '/seasonal',
          '/leaderboard',
          '/release-calendar',
          '/movies',
          '/tv-shows',
          '/top-rated',
          '/new-releases',
          '/genres',
          '/news',
          '/reviews',
          '/about',
          '/decade/',
          '/year/',
          '/privacy',
          '/terms',
          '/dmca',
          '/cookies',
          '/disclaimer',
          '/guide/',
          '/guides',
        ],
        disallow: [
          '/api/',
          '/auth/',
          '/embed/',
          '/stats',
          '/watchlist',
          '/profiles',
          '/select-profile',
          '/login',
          '/signup',
          '/settings',
          '/collections',
          '/activity',
          '/year-in-review',
        ],
        crawlDelay: 10,
      },
    ],
    sitemap: [
      `${siteUrl}/sitemap.xml`,
    ],
  };
}
